version: '3.8'

services:

  model-registry:
    build:
      context: .
      dockerfile: shared/model_registry.Dockerfile
    volumes:
      - ./core/model_registry:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - ALLOW_IFRAME=true
      - CORS_ORIGINS=*

  data-pipeline:
    image: apache/airflow:2.7.1
    volumes:
      - ./core/data_pipeline:/opt/airflow/dags
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__WEBSERVER__RBAC=false

  compliance:
    build:
      context: .
      dockerfile: shared/api.Dockerfile
    volumes:
      - ./core/compliance:/app
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - HOST=0.0.0.0
      - ALLOW_IFRAME=true
      - CORS_ORIGINS=*

  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - ./infrastructure/monitoring/prometheus-rules.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.5
    volumes:
      - ./infrastructure/monitoring/grafana-dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  frontend:
    build:
      context: services/frontend
    ports:
      - "51854:51854"
    environment:
      - PORT=51854
      - HOST=0.0.0.0
    depends_on:
      - model-registry
      - compliance