services:
  healthcare:
    build:
      context: .
      dockerfile: shared/api.Dockerfile
      target: builder
    volumes:
      - ./core/healthcare:/app
      - pip-cache:/root/.cache/pip
    ports:
      - "52209:52209"
    environment:
      - PORT=52209
      - HOST=0.0.0.0
      - ALLOW_IFRAME=true
      - CORS_ORIGINS=*
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "sleep 10 &&
             python -m uvicorn api.main:app --host 0.0.0.0 --port 52209 --reload --reload-dir /app --log-level debug"
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:52209/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    depends_on:
      model-registry:
        condition: service_healthy
      compliance:
        condition: service_healthy

  model-registry:
    build:
      context: .
      dockerfile: shared/model_registry.Dockerfile
      target: builder
    volumes:
      - ./core/model_registry:/app
      - pip-cache:/root/.cache/pip
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - ALLOW_IFRAME=true
      - CORS_ORIGINS=*
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "sleep 5 &&
             python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app --log-level debug"
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  compliance:
    build:
      context: .
      dockerfile: shared/api.Dockerfile
      target: builder
    volumes:
      - ./core/compliance:/app
      - pip-cache:/root/.cache/pip
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - HOST=0.0.0.0
      - ALLOW_IFRAME=true
      - CORS_ORIGINS=*
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "sleep 5 &&
             python -m uvicorn audit.main:app --host 0.0.0.0 --port 8001 --reload --reload-dir /app --log-level debug"
    healthcheck:
      test: ["CMD", "curl", "-v", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  frontend:
    build:
      context: services/frontend
      dockerfile: Dockerfile
    volumes:
      - ./services/frontend:/app
      - node-modules:/app/node_modules
      - npm-cache:/root/.npm
    ports:
      - "52209:52209"
    environment:
      - PORT=52209
      - HOST=0.0.0.0
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:52209
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: >
      sh -c "sleep 15 &&
             npm run dev -- --port 52209 --host 0.0.0.0"
    depends_on:
      healthcare:
        condition: service_healthy

volumes:
  pip-cache:
  node-modules:
  npm-cache:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400